config/routes.rb
Rails.application.routes.draw do
  

  ActiveAdmin.routes(self)
  resources :reviews do 
    resources :comments
    resource :bookmark


  end

resources :users

# one resource, one session
resource :session

  root "reviews#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :review
  belongs_to :user


# makes sure bookmark is unique. One bookmark per user, per review
# scope of each review is unique based on each user.. making sure we have one review per user
  validates :review, uniqueness: {scope: user}
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :review
  belongs_to :user

  validates :body, presence: true

  profanity_filter :body


end

app/models/review.rb
class Review < ApplicationRecord


    # add an association that has a 1-to-many relationship

    has_many :comments
    has_many :bookmarks

    #add association to the user
    belongs_to :user

    geocoded_by :address
    after_validation :geocode

    #add the photo uploader
    mount_uploader :photo, PhotoUploader

    validates :title, presence: true
    validates :body, length: {minimum: 10 }
    validates :score, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
    validates :restaurant, presence: true
    validates :address, presence: true

    def to_param 
        id.to_s + "-" + title.parameterize

    end


end

app/models/user.rb
class User < ApplicationRecord

has_many :reviews
has_many :comments
has_many :bookmarks

has_secure_password

validates :username, presence: true, uniqueness: true
validates :email, presence: true, uniqueness: true


#override user number param
def to_param
username
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

protect_from_forgery with: Exception


#before any page loads, find the current_user

before_action :find_current_user

#add in method to use in views

helper_method :is_logged_in?

def find_current_user 

    if session[:user_id].present?

    @current_user = User.find(session[:user_id])

    else
    @current_user = nil

    end

#check login statuc=s
    def check_login

        unless is_logged_in?
            redirect_to new_session_path
        end

    end


    #is the person logged in
    def is_logged_in?

        session[:user_id].present?
    end


    #check login status

    def check_admin
        @user = find_current_user

        unless @user.present? and @user.is_admin?
            redirect_to root_path
        end

    end

end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

before_action :check_login


def create 

#find the review we are bookmarking

@review = Review.find(params[:review_id])

@bookmark = @review.bookmarks.new
@bookmark.user = @current_user

@bookmark.save


#go back to review page
redirect_to review_path(@review)
end


def destroy

    @review = Review.find(params[:review_id])

    @review.bookmarks.where(user: @current_user).delete_all

    redirect_to review_path(@review)

end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        # review_id comes from our route.db
       @review = Review.find(params[:review_id]) 
       @comment = @review.comments.new(params.require(:comment).permit(:body))

       @comment.user = @current_user
       @comment.save
       redirect_to review_path(@review)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


    #check login can be found in application controller
    before_action :check_login, except: [:index, :show]
    
    def index
        # this is our list page for our reviews
        # finding info from URL
        @price = params[:price]
        @cuisine = params[:cuisine]
        @location = params[:location]

        # start with all the reviews
        @reviews = Review.all

        # filtering by price
        if @price.present?
            @reviews = @reviews.where(price: @price)
        
        end

        # filtering by cuisine
        if @cuisine.present?

            @reviews = @reviews.where(cuisine: @cuisine)
        end

        # filtering by location
        if @location.present?

            @reviews = @reviews.near(@location)

        end

    end


    def new
        # form for adding a new review
        @review = Review.new
    end


    def create
        #Take information from the form and add it to daatabase.
        @review = Review.new(form_params)

        # and then associate it with a user
        @review.user = @current_user

        # Save review to the database
        # we want to check if the model can be saved

        #if it is, back to home page

        #if it isnt, show the new form
        if @review.save
        
            redirect_to root_path

        else 
            # show the view for new.html.erb
            render "new"
        end


    end

    def show 
        # individual review page
        @review = Review.find(params[:id])

    end

    def destroy
    # find the individual review
    @review = Review.find(params[:id])
    # destroy

    if @review.user == @current_user 

    @review.destroy

    end
    # redirect to the home page because there is nothign else to go to.
    redirect_to root_path

    end

    def edit
        # find the individual review (to edit)
    @review = Review.find(params[:id])

    if @review.user != @current_user
        redirect_to root_path

    elsif @review.created_at < 1.hour.ago

        redirect_to review_path(@review)

    end

    end


    def update
    # find the individual review
    @review = Review.find(params[:id])


    if @review.user != @current_user
        redirect_to root_path

    else

             # update with the new info from the form
             if  @review.update(form_params)
                # redirect somewhere new
                    redirect_to review_path(@review)
            else
                render "edit"
            end
    end
       
    end

# things that we allow our users to do in form
    def form_params
        params.require(:review).permit(:title, :restaurant, :body, :score, :ambiance, :cuisine, :price, :address, :photo )

    end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    # login form    
    
    end

    def create
# actually try log in and out
        @form_data = params.require(:session)

        # pull out the username and password from teh form data.
        @username = @form_data[:username]
        @password = @form_data[:password]

        # lets check the user is who they say they are

        @user = User.find_by(username: @username).try(:authenticate, @password)

        # if there is a user present, redirect to homepage

            if @user 


                session[:user_id] = @user.id


            redirect_to root_path

            else render "new"
            end 
    end

    def destroy


        # log out

        # remove the session completely(built in with rails)

        reset_session

        #redirect to login page

        redirect_to new_session_path
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
@users = User.all
end

def show

    #so that url shows as users/rik
@user = User.find_by(username: params[:id])

end


def new
# form for adding a new user
@user = User.new
end

def create
# take params from the form
@user = User.new(form_params)
# create a new user
# if valid and it dsaves, go to the list users page

        if @user.save
            session[:user_id] = @user.id

            redirect_to root_path
        else
        render "new"

        end

end



def form_params
params.require(:user).permit(:username, :email, :password, :passord_confirmation)


end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for :page_title %> - Bien - The best restaurant in the world</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <header>
            <nav>
              
            <h1> 
            <%= link_to root_path do %>
            <%= image_tag "bien-logo.svg" %>
            <% end %>
            </h1>
            </nav>

            <h2>The best restaurants in the world</h2>

            <nav>
<%# 
            if the session we are in has a user_id, then we can add a review
            if the session doesnt have a user_id, display sign up and login %>
              <% if is_logged_in? %>

              <%= @current_user.username %>
                <%= link_to "Add a review", new_review_path %>

                <%= link_to "Log out" , session_path, method: :delete %>

              <% else %>
          <%= link_to "Sign up" , new_user_path %>

          <%= link_to "Log in" ,new_session_path %>

              <% end %>
           


            

            </nav>

  </header>


  
<main>
    <%= yield %>
</main>

    <footer>
    Copyright 2020 Bien Reviews
    </footer>
  </body>
</html>

app/views/reviews/_form.html.erb
    <%= simple_form_for @review do |f| %>


    <%= f.input :title %>
    <%= f.input :restaurant %>
    <%= f.input :address %>
    <%= f.input :photo %>
    <%= f.input :body %>
    <%= f.input :cuisine %>
    <%= f.input :price %>
    <%= f.input :score %>
    <%= f.input :ambiance %>
    <%= f.button :submit %>


    <% end %>

app/views/reviews/edit.html.erb
<h3>Edit your restaurant review</h3>

<%= render "form" %>

app/views/reviews/index.html.erb
<% content_for :page_title, "Homepage" %>

<nav class="filters">
<%= link_to "All Restaurants", root_path, active: { price: nil, cuisine: nil, location: nil }  %>

<div>

<%= active_link_to "$", root_path(price: 1, cuisine: @cuisine, location: @location), active: { price: 1 } %>
<%= active_link_to "$$", root_path(price: 2, cuisine: @cuisine, location: @location), active: { price: 2} %>
<%= active_link_to "$$$", root_path(price: 3, cuisine: @cuisine, location: @location), active: { price: 3 } %>
</div>

<div>
<%= active_link_to "Mexican", root_path(cuisine: "Mexican", price: @price, location: @location), active: {cuisine: "Mexican"} %>
<%= active_link_to "Thai", root_path(cuisine: "Asian", price: @price, location: @location), active: {cuisine: "Asian"} %>
<%= active_link_to "American", root_path(cuisine: "American", price: @price, location: @location), active: {cuisine: "American"} %>
</div>

<form action="/">
<input type="text" name="location" placeholder="search location..." value="<%= @location %>">
<input type="hidden" name="price" value="<%= @price %>">
<input type="hidden" name="cuisine" value="<%= @cuisine %>">
</form>


</nav>


<% @reviews.each do |review| %>

    <div class="review">

        <%= link_to review_path(review) do %>

         

            <%= image_tag review.photo.thumb.url %>

         

        <h2><%= review.title %></h2>
        <p><%= review.cuisine %>- 
        <%= pluralize review.comments.count, "comment" %>

    
        </p>

        <% end %>
    </div>
 <% end %>

app/views/reviews/new.html.erb
<% content_for :page_title, "Add a new Review" %>

<h3>Add your new restaurant review</h3>

<%= render "form" %>

app/views/reviews/show.html.erb
<% content_for :page_title, @review.title %>

<%= image_tag @review.photo.thumb.url %>


<h1><%= @review.title %></h1>
<h2><%= @review.restaurant %></h2>


<% if is_logged_in? %>
        <p> 
            <% if @review.bookmarks.where(user: @current_user).any? %>

            <%= link_to "Unbookmark", review_bookmark_path(@review), method: :delete %>
         
            <% else %>

            <%= link_to "Bookmark", review_bookmark_path(@review), method: :post %>
           
            <% end %>
        </p>
<% end %>

<h3>Bookmarked by...</h3>

<ul>
    <% @review.bookmarks.each do |bookmark| %>

    <li> <%= bookmark.user.username %></li>

    <% end %>

</ul>




<div class="score">
    <%= @review.score %> /10

</div>

<div class="user">
Posted by 
<% if @review.user.present? %>
<%= link_to @review.user.username, user_path(@review.user) %>

<% else %>
anonymous 
<% end %>


</div>


<% if @review.ambiance.present? %>

    <div class="ambiance">
    Ambiance: <%= @review.ambiance %>
    </div>

<% end %>
<% if @review.price.present? %>

    <div class="price">
    Price: <%= @review.price %>
    </div>


<% end %>

<% if @review.cuisine.present? %>

    <div class="cuisine">
    Cuisine: <%= @review.cuisine %>
    </div>

<% end %>

<div class="body">

<%= simple_format @review.body %>

</div>

<%# You can only edit and delete reviews if you are the one who posted it %>
<% if @review.user == @current_user %>

     <div class="actions">
        <%# show this link only if the review was submitted less than an hour ago %>
        <% if @review.created_at > 1.hour.ago %>

            <%= link_to "Edit this review", edit_review_path(@review) %>

        <% end %>
        <%= link_to "Delete this review", review_path(@review), method: :delete, data: { confirm: "Are you sure??"} %>

    </div>

<% end %>



<h3>Comments</h3>

<% @review.comments.order("created_at desc").each do |comment| %>
    <div class="comment">
        <%= simple_format comment.body %>

        <p class="posted">
Posted by 

<% if comment.user.present? %>

        <%=  link_to comment.user.username, user_path(comment.user) %>

        <% else %>

        anonymous

        <% end %>
        </p>

        <p class="posted">Posted <%= time_ago_in_words comment.created_at %> ago</p>
    </div>

<% end %>




<h3>Add a Comment</h3>

<%= simple_form_for [@review, Comment.new] do |f| %>

<%= f.input :body %>
<%= f.button :submit, "Add Comment" %>

<% end %>

app/views/users/index.html.erb
<h2>All users</h2>

<% @users.each do |user| %>

<%= user.username %> (<%= user.email %>)

<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>


<%= simple_form_for @user do |f| %>

<%= f.input :username %>
<%= f.input :email %>
<%= f.input :password %>
<%= f.input :password_confirmation %>
<%= f.button :submit, "Sign Up"%>

<% end %>

app/views/users/show.html.erb
<h2> <%= @user.username %> </h2>


<p> Their email is <%= @user.email %>